# Generated by Django 5.1.3 on 2024-11-15 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SpyCat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SpyCat.spycat')),
            ],
            options={
                'verbose_name': 'mission',
                'verbose_name_plural': 'missions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Notes', models.TextField(blank=True)),
                ('Complete_state', models.BooleanField(default=False)),
                ('Mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MissionTargets.mission')),
            ],
            options={
                'verbose_name': 'target',
                'verbose_name_plural': 'targets',
                'ordering': ['Name'],
            },
        ),
    ]
